# Generated by Django 3.0.6 on 2020-06-01 20:42

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('phonenumber', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('1', 'Alabama'), ('2', 'Alaska'), ('3', 'Arizona'), ('4', 'Arkansas'), ('5', 'California'), ('6', 'Colorado'), ('7', 'Connecticut'), ('8', 'Delaware'), ('9', 'Florida'), ('10', 'Georgia'), ('11', 'Hawaii'), ('12', 'Idaho'), ('13', 'Illinois'), ('14', 'Indiana'), ('15', 'Iowa'), ('16', 'Kansas'), ('17', 'Kentucky'), ('18', 'Louisiana'), ('19', 'Maine'), ('20', 'Maryland'), ('21', 'Massachusetts'), ('22', 'Michigan'), ('23', 'Minnesota'), ('24', 'Mississippi'), ('25', 'Missouri'), ('26', 'Montana'), ('27', 'Nebraska'), ('28', 'Nevada'), ('29', 'New Hampshire'), ('30', 'New Jersey'), ('31', 'New Mexico'), ('32', 'New York'), ('33', 'North Carolina'), ('34', 'North Dakota'), ('35', 'Ohio'), ('36', 'Oklahoma'), ('37', 'Oregon'), ('38', 'Pennsylvania'), ('39', 'Rhode Island'), ('40', 'South Carolina'), ('41', 'South Dakota'), ('42', 'Tennessee'), ('43', 'Texas'), ('44', 'Utah'), ('45', 'Vermont'), ('46', 'Virginia'), ('47', 'Washington'), ('48', 'West Virginia'), ('49', 'Wisconsin'), ('50', 'Wyoming')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=15)),
                ('DOB', models.DateField()),
                ('Gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=50)),
                ('k', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('degree', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('classroom', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=50)),
                ('languages', multiselectfield.db.fields.MultiSelectField(choices=[('english', 'English'), ('spanish', 'Spanish'), ('german', 'German'), ('chinese', 'Chinese'), ('hindi', 'Hindi'), ('french', 'French'), ('russian', 'Russian'), ('turkish', 'Turkish')], max_length=59, null=True)),
                ('genres', multiselectfield.db.fields.MultiSelectField(choices=[('classical', 'Classical'), ('rock', 'Rock'), ('musical Theater', 'Musical Theater'), ('country', 'country'), ('blues', 'Blues'), ('christian Contemporary', 'Christian Contemporary'), ('gospel', 'Gospel'), ('other', 'Other')], max_length=80, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application_field', models.SlugField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='tutors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('Tagline', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('images', models.ImageField(upload_to='media')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='onlinetutors.Category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
