# Generated by Django 3.0.6 on 2020-06-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutors',
            old_name='description',
            new_name='calendar_description',
        ),
        migrations.AddField(
            model_name='tutors',
            name='description_tutor',
            field=models.TextField(blank=True),
        ),
    ]
