# Generated by Django 3.0.6 on 2020-06-07 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0002_auto_20200605_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='days',
            field=models.DateTimeField(null=True),
        ),
    ]
