# Generated by Django 3.0.6 on 2020-06-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0002_remove_application_application_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='k',
            new_name='k12',
        ),
        migrations.AlterField(
            model_name='application',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='phonenumber',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
