# Generated by Django 3.0.6 on 2020-06-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0003_auto_20200601_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='confirm_password',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='application',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
