# Generated by Django 3.0.6 on 2020-06-07 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0003_tutors_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='days',
        ),
    ]
