# Generated by Django 3.0.6 on 2020-06-09 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='start_time',
        ),
    ]
