# Generated by Django 3.0.6 on 2020-06-03 21:59

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0006_auto_20200602_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='genres',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('classical', 'Classical'), ('rock', 'Rock'), ('musical Theater', 'Musical Theater'), ('country', 'country'), ('blues', 'Blues'), ('christian Contemporary', 'Christian Contemporary'), ('gospel', 'Gospel'), ('other', 'Other')], max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='languages',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('english', 'English'), ('spanish', 'Spanish'), ('german', 'German'), ('chinese', 'Chinese'), ('hindi', 'Hindi'), ('french', 'French'), ('russian', 'Russian'), ('turkish', 'Turkish')], max_length=59, null=True),
        ),
    ]
