# Generated by Django 3.0.6 on 2020-06-10 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0007_auto_20200609_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='calendar_description',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='title',
        ),
    ]
