# Generated by Django 3.0.6 on 2020-06-04 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0009_auto_20200603_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='address1',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='application',
            name='address2',
        ),
    ]
