# Generated by Django 3.0.6 on 2020-06-10 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0009_displaydates'),
    ]

    operations = [
        migrations.DeleteModel(
            name='displayDates',
        ),
    ]
