# Generated by Django 3.0.6 on 2020-06-10 00:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0010_delete_displaydates'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='select_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('M', 'Monday'), ('T', 'Tueasay'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('S', 'Saturday'), ('SU', 'Sunday')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='select_timings',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1', '6:30AM'), ('2', '7:30PM'), ('3', '8:30PM'), ('4', '9:30AM'), ('5', '10:30AM'), ('6', '11:30AM'), ('7', '12:30PM'), ('8', '1:30PM'), ('9', '2:30PM'), ('10', '3:30PM'), ('11', '4:30PM'), ('12', '5:30PM'), ('13', '6:30PM'), ('14', '7:30PM'), ('15', '8:30PM'), ('16', '9:30PM')], max_length=38, null=True),
        ),
    ]
