# Generated by Django 3.0.6 on 2020-06-10 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0011_auto_20200609_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='select_days',
        ),
        migrations.RemoveField(
            model_name='application',
            name='select_timings',
        ),
    ]
