# Generated by Django 3.0.6 on 2020-06-10 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0015_auto_20200610_1004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='select_days',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='select_timings',
        ),
    ]
