# Generated by Django 3.0.6 on 2020-06-10 21:09

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0017_auto_20200610_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='select_days',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=56, null=True),
        ),
    ]
