# Generated by Django 3.0.6 on 2020-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0018_tutors_select_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
