# Generated by Django 3.0.6 on 2020-06-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0019_auto_20200610_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='start_time',
        ),
        migrations.AddField(
            model_name='tutors',
            name='select_timings',
            field=models.CharField(blank=True, choices=[('6:30AM', '6:30AM'), ('7:30AM', '7:30AM'), ('8:30AM', '8:30AM'), ('9:30AM', '9:30AM'), ('10:30AM', '10:30AM'), ('11:30AM', '11:30AM'), ('12:30PM', '12:30PM'), ('1:30PM', '1:30PM'), ('2:30PM', '2:30PM'), ('3:30PM', '3:30PM'), ('4:30PM', '4:30PM'), ('5:30PM', '5:30PM'), ('6:30PM', '6:30PM'), ('7:30PM', '7:30PM'), ('8:30PM', '8:30PM'), ('9:30PM', '9:30PM')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='select_days',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
    ]
