# Generated by Django 3.0.6 on 2020-06-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0020_auto_20200610_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='select_days',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='select_timings',
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_days',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_timings',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
