# Generated by Django 3.0.6 on 2020-06-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0022_auto_20200611_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='enter_friday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_monday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_saturday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_sunday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_thursday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_tuesday',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_wednesday',
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_fridaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_mondaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_saturdaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_sundaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_thursdaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_tuesdaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_wednesdaytimings',
            field=models.CharField(blank=True, default='Not Available', max_length=50, null=True),
        ),
    ]
