# Generated by Django 3.0.6 on 2020-06-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0023_auto_20200611_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='enter_mondaytimings',
            field=models.CharField(blank=True, default='NotAvailable', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutors',
            name='enter_thursdaytimings',
            field=models.CharField(default='foobar', max_length=50, null=True),
        ),
    ]
