# Generated by Django 3.0.6 on 2020-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0024_auto_20200611_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutors',
            name='enter_thursdaytimings',
            field=models.CharField(default='foobar', editable=False, max_length=50, null=True),
        ),
    ]
