# Generated by Django 3.0.6 on 2020-06-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0025_auto_20200611_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutors',
            name='enter_fridaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_mondaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_saturdaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_sundaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_thursdaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_tuesdaytimings',
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='enter_wednesdaytimings',
        ),
    ]
