# Generated by Django 3.0.6 on 2020-06-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0026_auto_20200611_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutors',
            name='enter_fridaytimings',
            field=models.CharField(default='Not Available', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_mondaytimings',
            field=models.CharField(default='NotAvailable', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_saturdaytimings',
            field=models.CharField(default='Not Available', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_sundaytimings',
            field=models.CharField(default='Not Available', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_thursdaytimings',
            field=models.CharField(default='NotAvailable', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_tuesdaytimings',
            field=models.CharField(default='NotAvailable', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='tutors',
            name='enter_wednesdaytimings',
            field=models.CharField(default='NotAvailable', editable=False, max_length=50),
        ),
    ]
