# Generated by Django 3.0.6 on 2020-08-24 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0031_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
