# Generated by Django 3.0.6 on 2020-08-24 22:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0033_auto_20200824_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratings',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratings',
            name='updated',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2020, 8, 24, 22, 46, 48, 549458, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
