# Generated by Django 3.0.6 on 2020-09-15 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0034_auto_20200824_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratings',
            name='updated',
        ),
    ]
