# Generated by Django 3.0.6 on 2020-09-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0035_remove_ratings_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='username',
            field=models.CharField(max_length=32),
        ),
    ]
