# Generated by Django 3.0.6 on 2020-09-17 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0041_auto_20200917_1143'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ratings',
        ),
    ]
