# Generated by Django 3.0.6 on 2020-09-17 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0045_auto_20200917_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratings',
            name='tutorname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onlinetutors.tutors'),
        ),
    ]
