# Generated by Django 3.0.6 on 2020-09-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinetutors', '0046_auto_20200917_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ratings',
        ),
    ]
